# TIPOS PRIMITIVOS DE SAIDAS DE DADOS: 
# int (NUMERO INTEIRO) , float (NUMERO REAIS DE PONTO FLUTUANTE), bool(BOLEANOS), str (STRING).

# int = NUMERO INTEIROS EX.1, 2, 3, 4, 0, - 1 - 10, 9875 
# float = NUMERO REAIS OU NUMEROS DE PONTO FLUTUANTE EX. (4.5), (0.076), (-15.223)
# bool = NUMEROS BOLEANOS OU LÓGICOS EX. True (VERDADEIRO) False (FALSO)
# str = STRING É UMA SEQUENCIA DE LETRAS, NUMEROS OU SIMBOLOS. EX.("NOME", "1234", "$+%#@") FICAM ENTRE AS ASPAS.